### ISSUE TITLE
关于自定义rebot回复的内容

### ISSUE THREAD

**Issue by lwhhhh** [limicala/wx_robot#1]
相关的内容写在一份配置文件rule.conf.

格式为:

[key_word]:[reply content]

例子:

"软件测试作业" : "第三次和第四次实验报告,周四前上传"

**Comment by limicala** [comment]
删除的话把该key的内容设成""，还是删除整个key的所有信息

**Comment by lwhhhh** [comment]
@limicala 感觉整个都删除好一点吧 ?
