### ISSUE TITLE
rule.py 无法保存对象

### ISSUE THREAD

**Issue by limicala** [limicala/wx_robot#5]

**Comment by lwhhhh** [comment]
@limicala 我这边无法重现这个bug.测试的脚本更新在config_test.py里

**Comment by lwhhhh** [comment]
Could we communicate in English ? Tthough this is a bit challenging. @limicala

**Comment by limicala** [comment]
😂Oh yeah！challenging！

**Comment by limicala** [comment]
It still wrong!And I find rule.py  , the method "__read__" .

When it fails to deserialize, it set the __rule as an empty dictionary.

**Comment by lwhhhh** [comment]
@limicala  let me test

**Comment by lwhhhh** [comment]
update unit test to test the error and pass it,so I close this issue fristly
