### ISSUE TITLE
作业操作格式说明

### ISSUE THREAD

**Issue by limicala** [limicala/wx_robot#6]
添加格式例子：添加\nkey1:[val1,val2]\nkey2:[val1,val2]
修改格式例子：修改\nkey1:[val1,val2]\nkey2:[val1,val2]

查看作业时
显示所有作业
还是只显示列表中的第一个

**Comment by limicala** [comment]
如果添加格式和修改格式是一样的话，那就默认key值相同时后来添加覆盖前面的吧

**Comment by lwhhhh** [comment]
从实际情况看应该是显示所有的作业好点吧?如果只显示第一个的话,我们还要纠结如何显示剩余作业...

**Comment by lwhhhh** [comment]
嗯嗯,现在默认就是这种逻辑

**Comment by limicala** [comment]
那格式就先这样了，你觉得没问题的话你就关闭这个issue了

**Comment by lwhhhh** [comment]
好嘞 @limicala

**Comment by lwhhhh** [comment]
这种一步步推进工作的感觉好爽啊 @limicala

**Comment by limicala** [comment]
我再说下格式吧，就是我们下午讨论的那样

格式：

课程1:
作业1
作业2
课程2:
作业1
作业2
作业3

好啦
